### PR TITLE
Touch all elc files after installation

### PR DESCRIPTION
**Pull request by snogge**
To avoid

Recursive load: "/usr/local/share/emacs/25.2/lisp/jka-compr.el.gz",
 "/usr/local/share/emacs/25.2/lisp/jka-compr.el.gz",
 "/usr/local/share/emacs/25.2/lisp/jka-compr.el.gz",
 "/usr/local/share/emacs/25.2/lisp/jka-compr.el.gz",
 "/usr/local/share/emacs/25.2/lisp/jka-compr.el.gz",
 "/usr/local/share/emacs/25.2/lisp/emacs-lisp/autoload.el.gz"

### CODE REVIEW

**Comment by Silex** [comment]
Hello!

Do you mean there's some sort of bug in `make install` that requires this workaround? Does this bug affect all versions?

On a side note you used tabs instead of spaces in your patch, you'd change that.

**Comment by Silex** [comment]
Also I don't quite fully understand the bug, can you describe it a bit more?

**Comment by snogge** [comment]
I've changed tabs to space now.  I hope I didn't miss anything.

For some builds - not entirely reproducible - I got errors like the one in the commit message.  Googling it I found bbatsov/prelude#938 and purcell/emacs.d#340 . Both indicate that the timestamps of the el.gz and elc files are somhow wrong. touching the elc files make sure that they are newer. 

I don't know which versions were affected.  Maybe it is a problem with parallel install?

**Comment by Silex** [comment]
> I don't know which versions were affected. Maybe it is a problem with parallel install?

If it's the case I think a better fix would be `make -j 8 && make install`

But I want to reproduce the problem first. I tried this:

``` bash
for i in 24.4 24.5 25.1 25.2 25.3 26.1; do
  docker pull silex/emacs:$i
  docker run -it --rm silex/emacs:$i
done
```

All the images worked fine. Can you tell me a bit more how to trigger it or link me to a build where your error happened?

**Comment by snogge** [comment]
I originally added this commit in my fork on November 11 2018, so I no longer remember the details :(

It seems from the bug reports I mentioned above that you have to `(setq load-prefer-newer t)` to trigger the bug.  This is not something I do explicitly in my CI-jobs, but maybe cask does?

What is not obvious from the commit message, and something I just remembered, is that it is not the build that has these problems, but actual use of the image. 
I just found what may be my first CI-job that failed with this error, on a 25.3-alpine image variant. 
https://circleci.com/bb/olanilsson/buttercup-junit/1155 .  The images used were produced by this travis job https://travis-ci.org/snogge/docker-emacs/builds/451580981 .
The log https://api.travis-ci.org/v3/job/451580984/log.txt is for job 54.3 that produces the actual image used in the circleci job 1155, specifically 
`25-alpine-ci: digest: sha256:67c07bd55cd2998fa0107352000316734b903bbde576c9f6cd4022b35c405685 size: 1163`

I don't see anything obvious in the logs, but I seem to remember that the actual files involved are special somehow.

**Comment by snogge** [comment]
I just had a thought, maybe the problem is caused by the fact that you have chosen to use just `make install`instead of `make && make install`.  If the make task that installs the `.el.gz` file executes before the compilation task or the task that installs the `elc`file, I guess the file times could be messed up.  I have not checked the Makefiles to see whether this is a possible scenario.

**Comment by Silex** [comment]
> I just had a thought, maybe the problem is caused by the fact that you have chosen to use just `make install`instead of `make && make install`. If the make task that installs the `.el.gz` file executes before the compilation task or the task that installs the `elc`file, I guess the file times could be messed up. I have not checked the Makefiles to see whether this is a possible scenario.

This is why I proposed this in my previous comment:

> > I don't know which versions were affected. Maybe it is a problem with parallel install?
> 
> If it's the case I think a better fix would be `make -j 8 && make install`

Anyway, I don't think the fix I proposed would hurt, so we can do that.

Do you want to change your commit for that fix? I can also do it, tell me.

**Comment by Silex** [comment]
It was so simple I did it quickly, reopen if needed.

**Comment by snogge** [comment]
That's great, I'll try it and reopen if needed. 
Thank you.

**Pull request closed without merging**
