### PR TITLE
Build with modules support

### PR DESCRIPTION
**Pull request by Silex**
Do you think we should enable it for all images or only the `-dev` variants?

### CODE REVIEW

**Comment by Silex** [comment]
@justinbarclay: I'm not really familiar with modules, is this something that makes sense for all images?

**Comment by justinbarclay** [comment]
I'm not that familiar with it either, just enough to work on my current project. I think it opens up the possibilities of what someone can do with Emacs, but on the other hand there are not that many modules out there that currently take advantage of shared libraries.

**Comment by Silex** [comment]
Hum alright, then let's merge for all `25+` images.

**Comment by justinbarclay** [comment]
I'm getting a lot more green on my tests now because of you!  Thanks for this PR and all of your work maintaining this repo :)

**Pull request merged**
