### PR TITLE
Further specify "Inherits from" for alpine versions

### PR DESCRIPTION
**Pull request by agsdot**

### CODE REVIEW

**Comment by agsdot** [comment]
@Silex, thank you for providing these emacs docker images. I'm thinking that the alpine docker image tags in the readme need to be updated/clarified.

**Comment by Silex** [comment]
Good catch! Thanks :+1:

**Comment by agsdot** [comment]
You're welcome @Silex! And also thanks once again for providing these fantastic docker images for emacs. Much appreciated!

**Comment by Silex** [comment]
Thanks for the kind words. I'm a bit overwhelmed at the moment, I can't find time to fix the alpine images issues :disappointed:

**Pull request merged**
